### ISSUE TITLE
DC Nextbus down

### ISSUE THREAD

**Issue by juantana** [j-ro/BusTrackDC#1]
Dec 19-20 still won’t open, freezes on open screen, iOS 11.2.1

**Comment by j-ro** [comment]
Hi there, no problems here, or with other users. I'd suggest deleting the app and reinstalling. Let me know if that doesn't work!

**Comment by juantana** [comment]
That worked, thanks!

Sent from my iPhone

On Dec 20, 2017, at 9:45 AM, Jason Rosenbaum <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi there, no problems here, or with other users. I'd suggest deleting the app and reinstalling. Let me know if that doesn't work!

**Comment by j-ro** [comment]
Great to hear!
