### ISSUE TITLE
Missing Stop

### ISSUE THREAD

**Issue by juantana** [j-ro/BusTrackDC#2]
Hi - the 96 stop at Massachusetts and Columbus Circle says "an error occurred" even tho it shows one the WMATA page.  I tried un-adding it as favorite and re-adding with the same error - even clicking from the map errors.  Can you take a look?  Thanks!

**Comment by j-ro** [comment]
Thanks for the report! This appears to be an error with WMATA's apis. This stop shows up in the list of stops near that location, but when you try to get bus predictions for it WMATA's api says the stop doesn't exist. I've reported the error to them.

**Comment by juantana** [comment]
Thank you!!!! Love the app!

Sent from my iPad

On Jun 18, 2019, at 4:30 PM, Jason Rosenbaum <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #2<https://github.com/j-ro/BusTrackDC/issues/2>.

**Comment by j-ro** [comment]
Great to hear! Thanks for the report!

**Comment by j-ro** [comment]
WMATA says this is fixed, can you let me know if it is for you?

**Comment by juantana** [comment]
it is fixed finally! thanks for checking on it for me!

Sent from my iPhone

On Jul 17, 2019, at 3:43 PM, Jason Rosenbaum <notifications@github.com<mailto:notifications@github.com>> wrote:


WMATA says this is fixed, can you let me know if it is for you?

**Comment by j-ro** [comment]
great news!
