### ISSUE TITLE
Separate 38B Rosslyn Stop into Two Stops?

### ISSUE THREAD

**Issue by ghost** [j-ro/BusTrackDC#60]
Great app--thank you. This app makes my commute very easy and saves me lots of time.
The 38B bus route stop at N Moore St + Rosslyn Station Bus Bay E accounts for both directions (West to Ballston and East to Farragut Square). In the app, this stop only shows the route direction of the next arrival, but doesn't indicate the direction of subsequent arrivals. Understand this may flow directly from Next Bus, but would it be possible to break this out into two separate stops, one for each direction of the 38B route? WMATA Next Bus stop page address below for reference. Thank you.

http://www.wmata.com/rider_tools/nextbus/arrivals.cfm?r=38B&d=38B_38B_1&s=14089&ts=18802

**Comment by j-ro** [comment]
Thanks for reporting this! I'll see what I can do. This stop is unusual because it contains both directions, so it's not a case I've handled before. I'll have to think a bit and figure out the best way to sort out the information wmata is giving me for this stop.

**Comment by rodrigojuan** [comment]
Great--thanks, j-ro. Keep up the good work

**Comment by j-ro** [comment]
This should be fixed in the next version, just submitted to various app stores! Apple will take a week or so to be live, Android is quicker. Let me know if it doesn't work for you when it comes out!
